version: '3.9'

services:

  web:
    build: .

    container_name: booking_api_container

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/bookingdb

  db:
    image: postgres:15

    container_name: postgres_container

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookingdb

    ports:
      - "5432:5432"